In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_PATH = PROJECT_ROOT / "data" / "raw" / "ExportStagesentreprisessujets2020-2027.xlsx"

df_raw = pd.read_excel(RAW_PATH)
df = df_raw.copy()

In [20]:
column_inspection = pd.DataFrame({
    "column": df.columns.astype(str),
    "non_null_count": df.notna().sum().values,
    "example_values": [df[column].dropna().head(3).tolist() for column in df.columns],
})
display(column_inspection)

,column,non_null_count,example_values
0,Année académique,2288,"[2020/2021, 2020/2021, 2020/2021]"
1,N° Convention de stage,2292,"[SIA - 0 -, PFE - 0 -, PFE - 4522 -]"
2,Date début,2281,"[2020-07-06 00:00:00, 2020-09-01 00:00:00, 202..."
3,Date fin,2280,"[2020-12-24 00:00:00, 2021-02-12 00:00:00, 202..."
4,Durée totale (mois),2292,"[0.0, 0.0, 0.0]"
5,Type de Stage,2292,"[SIA, PFE, PFE]"
6,Nature du stage,1839,"[Stage en entreprise, Stage en laboratoire, St..."
7,N° étudiant,2292,"[2025133.0, 2024195.0, 2024223.0]"
8,NOM de l'élève,2292,"[FEUILLET, PRIGENT, DEXEMPLE]"
9,Prénom de l'élève,2292,"[Kerian, Capucine, Thibault]"
10,Entreprise,2260,"[FLORIDA INSTITUTE OF TECHNOLOGY, JET AVIATION..."
11,Titre du stage,2292,[OPTICAL CHARACTERISATION AND ENVIRONMENTAL DU...
12,Descriptif du Stage,2280,[The project concerns the optical properties o...
13,Adresse,2291,"[6 BABBAGE WAY, EXETER, EX5 2FN, 8 RUE DE LA G..."
14,Code postal,2287,"[0, 1347, 2017]"
15,Ville,2292,"[EXETER, LE SENTIER, BOUDRY]"
16,Entreprise (Lieu Stage),542,"[JET AVIATION, FARM3, AICM]"
17,CP (Lieu Stage),535,"[74100, 25300, 10053]"
18,Ville (Lieu Stage),544,"[COLLONGES, VERRIÈRES DE JOUX, LES BERGES DU LAC]"
19,Pays (Lieu Stage),630,"[FRANCE, TUNISIE, BELGIQUE]"
20,Date soutenance,1588,"[2021-02-03 00:00:00, 2021-04-01 00:00:00, 202..."
21,Référent pédagogique (mail),2279,"[sarah.bure@supmicrotech.fr, joel.imbaud@supmi..."
22,Référent pédagogique (mail).1,2279,"[BURE Sarah, IMBAUD Joël, LENOIR Henrik]"

In [2]:
print(f"Rows: {df_raw.shape[0]:,} | Columns: {df_raw.shape[1]:,}")
display(df_raw.head())
display(df_raw.describe(include="all").T)

Rows: 2,294 | Columns: 23

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,...,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
0,NaN,SIB - 4255 -,2025-12-22,NaT,0.0,SIB,NaN,NaN,TEST,Eudonet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,support+2@eudonet.com,TEST2 Eudonet
1,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,...,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
2,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,...,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
3,NaN,PFE - 0 -,NaT,NaT,0.0,PFE,NaN,2024195.0,PRIGENT,Capucine,...,8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,NaN,PFE - 4522 -,NaT,NaT,0.0,PFE,NaN,2024223.0,DEXEMPLE,Thibault,...,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN,NaT,NaN,NaN

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Année académique,2288,7,2023/2024,379,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N° Convention de stage,2294,2293,SIA - 0 -,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date début,2282,NaN,NaN,NaN,2023-08-17 21:39:16.879930,2020-06-29 00:00:00,2022-02-07 00:00:00,2023-09-01 00:00:00,2025-02-17 00:00:00,2027-02-15 00:00:00,NaN
Date fin,2280,NaN,NaN,NaN,2024-01-24 18:39:47.368421,2020-11-06 00:00:00,2022-07-29 00:00:00,2024-01-31 00:00:00,2025-08-01 00:00:00,2027-07-11 00:00:00,NaN
Durée totale (mois),2294.0,NaN,NaN,NaN,5.325959,0.0,5.0,5.5,5.97,13.13,1.159058
Type de Stage,2294,8,PFE,963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nature du stage,1839,5,Stage en entreprise,1525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N° étudiant,2293.0,NaN,NaN,NaN,2021281.460968,2015120.0,2020033.0,2021164.0,2023088.0,2026034.0,2040.696625
NOM de l'élève,2294,1359,NICOLAS,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Prénom de l'élève,2294,694,Antoine,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Entreprise,2260,1199,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Titre du stage,2293,2071,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Descriptif du Stage,2281,2256,The visiting scholar will assist on the ongoin...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Adresse,2292,1525,26 RUE DE L'EPITAPHE,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Code postal,2288,917,25000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ville,2293,924,BESANCON,235,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Entreprise (Lieu Stage),542,389,DASTRI,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CP (Lieu Stage),535,273,25000,128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ville (Lieu Stage),544,281,BESANCON,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pays (Lieu Stage),630,30,FRANCE,434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date soutenance,1588,NaN,NaN,NaN,2023-12-24 10:40:12.090680,2020-10-05 00:00:00,2022-04-07 00:00:00,2023-06-22 00:00:00,2025-10-09 00:00:00,2026-10-08 00:00:00,NaN
Référent pédagogique (mail),2281,132,eric.merat@supmicrotech.fr,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Référent pédagogique (mail).1,2281,76,STHAL Fabrice,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Suppression des doublons exacts
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates().copy()

duplicates_after = df.duplicated().sum()

print(f"Doublons supprimés : {duplicates_before}")
print(f"Doublons restants : {duplicates_after}")

Doublons supprimés : 1
Doublons restants : 0

In [4]:
df.loc[df["Titre du stage"].isna()]

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,...,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
0,NaN,SIB - 4255 -,2025-12-22,NaT,0.0,SIB,NaN,NaN,TEST,Eudonet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,support+2@eudonet.com,TEST2 Eudonet

In [5]:
before = df.shape[0]
df = df.dropna(subset=["Titre du stage"]).copy()
after = df.shape[0]

print(f"Lignes supprimées : {before - after}")
print(f"Nouvelle taille du DataFrame : {df.shape}")

Lignes supprimées : 1
Nouvelle taille du DataFrame : (2292, 23)

In [ ]:
df.loc[df["Ville"].isna()]

Empty DataFrame
Columns: [Année académique, N° Convention de stage, Date début, Date fin, Durée totale (mois), Type de Stage, Nature du stage, N° étudiant, NOM de l'élève, Prénom de l'élève, Entreprise, Titre du stage, Descriptif du Stage, Adresse, Code postal, Ville, Entreprise (Lieu Stage), CP (Lieu Stage), Ville (Lieu Stage), Pays (Lieu Stage), Date soutenance, Référent pédagogique (mail), Référent pédagogique (mail).1]
Index: []

[0 rows x 23 columns]

In [55]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean().mul(100),
}).sort_values("missing_count", ascending=False)
display(missing_summary)

                               missing_count  missing_percent
Entreprise (Lieu Stage)                 1747        76.221640
CP (Lieu Stage)                         1744        76.090750
Ville (Lieu Stage)                      1744        76.090750
Pays (Lieu Stage)                       1646        71.815009
Date soutenance                          704        30.715532
Nature du stage                          453        19.764398
Entreprise                                32         1.396161
Référent pédagogique (mail)               13         0.567190
Référent pédagogique (mail).1             13         0.567190
Descriptif du Stage                       12         0.523560
Date fin                                  12         0.523560
Date début                                11         0.479930
Code postal                                5         0.218150
Année académique                           4         0.174520
Adresse                                    1         0.043630
Type de Stage                              0         0.000000
Durée totale (mois)                        0         0.000000
N° Convention de stage                     0         0.000000
Prénom de l'élève                          0         0.000000
Titre du stage                             0         0.000000
N° étudiant                                0         0.000000
NOM de l'élève                             0         0.000000
Ville                                      0         0.000000

In [15]:
df.loc[df["Date fin"].isna()]

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,...,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
1,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,...,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
3,NaN,PFE - 0 -,NaT,NaT,0.0,PFE,NaN,2024195.0,PRIGENT,Capucine,...,8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,NaN,PFE - 4522 -,NaT,NaT,0.0,PFE,NaN,2024223.0,DEXEMPLE,Thibault,...,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5,NaN,SIB - 0 -,NaT,NaT,0.0,SIB,NaN,2025212.0,VERET,Louis,...,150 WEST UNIVERSITY BOULEVARD,32901-6975,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2192,2025/2026,SD - 4429 - 2025/2026,NaT,NaT,0.0,SD,NaN,2025153.0,JEANSON,Nathan,...,1100 NOTRE-DAME ST W,H3C 1K3,MONTRÉAL,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2199,2026/2027,SIA - 4413 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025160.0,LARRE,Corentin,...,150 W. UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2229,2026/2027,SD - 4451 - 2026/2027,2026-08-24,NaT,0.0,SD,NaN,2025098.0,ATMANE,Youssef,...,"24, RUE DE L'EPITAPHE",CDD,BESANÇON,NaN,NaN,NaN,NaN,NaT,nicolas.bodin@supmicrotech.fr,BODIN Nicolas
2243,2026/2027,SIA - 4468 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025195.0,RESCOURIO,Maxence,...,150 WEST UNIVERSITY BOULEVARD,FL 32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,morvan.ouisse@supmicrotech.fr,OUISSE Morvan
2249,2026/2027,SIA - 4476 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025132.0,FESTOC,Nathan,...,150 WEST UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,FRANCE,NaT,NaN,NaN
2259,2026/2027,SIA - 4486 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2261,2026/2027,SIA - 4488 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2264,2026/2027,SIA - 4491 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025171.0,MASSOT,Mathys,...,8 RUE GÉRARD MANTION,25000,BESANCON,NaN,NaN,NaN,NaN,NaT,samuel.margueron@supmicrotech.fr,MARGUERON Samuel

In [16]:
missing_summary = (
    df.isna()
      .sum()
      .to_frame("missing_count")
)

missing_summary["missing_percent"] = (
    missing_summary["missing_count"] / len(df) * 100
)

missing_summary = missing_summary.sort_values(
    "missing_percent",
    ascending=False
)

display(missing_summary)

                               missing_count  missing_percent
CP (Lieu Stage)                         1757        76.657941
Entreprise (Lieu Stage)                 1750        76.352531
Ville (Lieu Stage)                      1748        76.265271
Pays (Lieu Stage)                       1662        72.513089
Date soutenance                          704        30.715532
Nature du stage                          453        19.764398
Entreprise                                32         1.396161
Référent pédagogique (mail)               13         0.567190
Référent pédagogique (mail).1             13         0.567190
Descriptif du Stage                       12         0.523560
Date fin                                  12         0.523560
Date début                                11         0.479930
Code postal                                5         0.218150
Année académique                           4         0.174520
Adresse                                    1         0.043630
Type de Stage                              0         0.000000
Durée totale (mois)                        0         0.000000
N° Convention de stage                     0         0.000000
Prénom de l'élève                          0         0.000000
Titre du stage                             0         0.000000
N° étudiant                                0         0.000000
NOM de l'élève                             0         0.000000
Ville                                      0         0.000000

In [17]:
display(
    df.loc[
        df["Titre du stage"].isna(),
        ["Titre du stage", "Descriptif du Stage", "Entreprise", "Type de Stage"]
    ]
)

Empty DataFrame
Columns: [Titre du stage, Descriptif du Stage, Entreprise, Type de Stage]
Index: []

In [18]:
display(
    df.loc[
        df["Date soutenance"].isna(),
        ["Date début", "Date fin", "Durée totale (mois)", "Type de Stage"]
    ]
)

     Date début   Date fin  Durée totale (mois) Type de Stage
1           NaT        NaT                 0.00           SIA
3           NaT        NaT                 0.00           PFE
4           NaT        NaT                 0.00           PFE
5           NaT        NaT                 0.00           SIB
96   2020-09-28 2020-12-10                 2.40           SNO
...         ...        ...                  ...           ...
2289 2026-09-21 2027-01-31                 4.40           PFE
2290 2026-09-08 2027-02-05                 5.00           SIA
2291 2026-09-09 2027-02-09                 5.10           PFE
2292 2026-09-14 2026-12-11                 2.93           SIA
2293 2026-10-05 2027-02-19                 4.57           PFE

[704 rows x 4 columns]

In [19]:
display(df[df["Durée totale (mois)"] == 0])

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,...,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
1,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,...,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
3,NaN,PFE - 0 -,NaT,NaT,0.0,PFE,NaN,2024195.0,PRIGENT,Capucine,...,8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,NaN,PFE - 4522 -,NaT,NaT,0.0,PFE,NaN,2024223.0,DEXEMPLE,Thibault,...,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5,NaN,SIB - 0 -,NaT,NaT,0.0,SIB,NaN,2025212.0,VERET,Louis,...,150 WEST UNIVERSITY BOULEVARD,32901-6975,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2192,2025/2026,SD - 4429 - 2025/2026,NaT,NaT,0.0,SD,NaN,2025153.0,JEANSON,Nathan,...,1100 NOTRE-DAME ST W,H3C 1K3,MONTRÉAL,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2199,2026/2027,SIA - 4413 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025160.0,LARRE,Corentin,...,150 W. UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2229,2026/2027,SD - 4451 - 2026/2027,2026-08-24,NaT,0.0,SD,NaN,2025098.0,ATMANE,Youssef,...,"24, RUE DE L'EPITAPHE",CDD,BESANÇON,NaN,NaN,NaN,NaN,NaT,nicolas.bodin@supmicrotech.fr,BODIN Nicolas
2243,2026/2027,SIA - 4468 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025195.0,RESCOURIO,Maxence,...,150 WEST UNIVERSITY BOULEVARD,FL 32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,morvan.ouisse@supmicrotech.fr,OUISSE Morvan
2249,2026/2027,SIA - 4476 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025132.0,FESTOC,Nathan,...,150 WEST UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,FRANCE,NaT,NaN,NaN
2259,2026/2027,SIA - 4486 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2261,2026/2027,SIA - 4488 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2264,2026/2027,SIA - 4491 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025171.0,MASSOT,Mathys,...,8 RUE GÉRARD MANTION,25000,BESANCON,NaN,NaN,NaN,NaN,NaT,samuel.margueron@supmicrotech.fr,MARGUERON Samuel

In [21]:
pd.set_option("display.max_columns", None)

display(df[df["Durée totale (mois)"] == 0])

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,Entreprise,Titre du stage,Descriptif du Stage,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
1,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,NaN,OPTICAL CHARACTERISATION AND ENVIRONMENTAL DUR...,The project concerns the optical properties of...,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
3,NaN,PFE - 0 -,NaT,NaT,0.0,PFE,NaN,2024195.0,PRIGENT,Capucine,NaN,STAGE SAV,"• Cartographier les processus SAV (réception, ...",8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,NaN,PFE - 4522 -,NaT,NaT,0.0,PFE,NaN,2024223.0,DEXEMPLE,Thibault,NaN,REVUE GLOBALE DE LA STRATÉGIE D'ASSURANCE QUAL...,-Réviser globalement la stratégie d’assurance ...,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5,NaN,SIB - 0 -,NaT,NaT,0.0,SIB,NaN,2025212.0,VERET,Louis,FLORIDA INSTITUTE OF TECHNOLOGY,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...,Participation à un projet de recherche au sein...,150 WEST UNIVERSITY BOULEVARD,32901-6975,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2192,2025/2026,SD - 4429 - 2025/2026,NaT,NaT,0.0,SD,NaN,2025153.0,JEANSON,Nathan,NaN,STAGE DE RECHERCHE - MÉTHODOLOGIES D'ÉTUDES DE...,Étude de plusieurs méthodologies de contrôle p...,1100 NOTRE-DAME ST W,H3C 1K3,MONTRÉAL,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2199,2026/2027,SIA - 4413 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025160.0,LARRE,Corentin,NaN,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...,The proposed project consists of developing an...,150 W. UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2229,2026/2027,SD - 4451 - 2026/2027,2026-08-24,NaT,0.0,SD,NaN,2025098.0,ATMANE,Youssef,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,TRIBOLOGIE DU BOIS : RÉALISATION D’ESSAIS EXPÉ...,L’objectif de ce stage est d’étudier le compor...,"24, RUE DE L'EPITAPHE",CDD,BESANÇON,NaN,NaN,NaN,NaN,NaT,nicolas.bodin@supmicrotech.fr,BODIN Nicolas
2243,2026/2027,SIA - 4468 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025195.0,RESCOURIO,Maxence,FLORIDA INSTITUTE OF TECHNOLOGY,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...,The proposed project consists of developing an...,150 WEST UNIVERSITY BOULEVARD,FL 32901,MELBOURNE,NaN,NaN,NaN,NaN,NaT,morvan.ouisse@supmicrotech.fr,OUISSE Morvan
2249,2026/2027,SIA - 4476 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025132.0,FESTOC,Nathan,INSTITUT TECHNOLOGIQUE DE FLORIDE,AMORTISSEUR À MASSE OSCILLANTE POUR L'ATTÉNUAT...,Le projet proposé consiste à mettre au point d...,150 WEST UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,FRANCE,NaT,NaN,NaN
2259,2026/2027,SIA - 4486 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,THALES AVIONICS SAS,STAGE INGÉNIEUR MATÉRIAUX : CARACTÉRISATION ET...,Élaborer et développer une méthode de caractér...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2261,2026/2027,SIA - 4488 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025169.0,MAHRA,Amir,THALES AVIONICS SAS,STAGE INGÉNIEUR MATÉRIAUX : CARACTÉRISATION ET...,Élaborer et développer une méthode de caractér...,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,NaN,NaN,NaN,NaT,philippe.stempfle@supmicrotech.fr,STEMPFLE Philippe
2264,2026/2027,SIA - 4491 - 2026/2027,NaT,NaT,0.0,SIA,NaN,2025171.0,MASSOT,Mathys,GRUPO ANTOLIN BESANCON,MODÉLISATION ET MESURES PHOTOMÉTRIQUES .,Faire des mesures photométriques ainsi que mod...,8 RUE GÉRARD MANTION,25000,BESANCON,NaN,NaN,NaN,NaN,NaT,samuel.margueron@supmicrotech.fr,MARGUERON Samuel

In [22]:
(df["Durée totale (mois)"] == 0).sum()

np.int64(12)

In [23]:
from difflib import SequenceMatcher

comparison = df[
    df["Entreprise"].notna() &
    df["Entreprise (Lieu Stage)"].notna()
][["Entreprise", "Entreprise (Lieu Stage)"]].copy()

comparison["similarity"] = comparison.apply(
    lambda row: SequenceMatcher(
        None,
        str(row["Entreprise"]).lower().strip(),
        str(row["Entreprise (Lieu Stage)"]).lower().strip()
    ).ratio(),
    axis=1
)

display(
    comparison.sort_values("similarity", ascending=False)
)

,Entreprise,Entreprise (Lieu Stage),similarity
2290,FEMTO-ST / DÉPARTEMENT MÉCANIQUE APPLIQUÉE,FEMTO-ST / DÉPARTEMENT MÉCANIQUE APPLIQUÉE,1.000000
2133,ARQUUS,ARQUUS,1.000000
2282,FEMTO-ST,FEMTO-ST,1.000000
119,ROBERT BOSCH GMBH,ROBERT BOSCH GMBH,1.000000
122,SEGULA MATRA AUTOMOTIVE,SEGULA MATRA AUTOMOTIVE,1.000000
...,...,...,...
1100,LORIA UMR 7503,UNIVERSITE D'AIX MARSEILLE,0.050000
92,CTRE NAT DE LA RECHERCHE SCIENTIFIQUE,IPAG,0.048780
18,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,FARMCUBE,0.028571
1269,ONCF,EMIM,0.000000
13,SERRU,AICM,0.000000

In [24]:
comparison["similarity_percent"] = comparison["similarity"] * 100

display(
    comparison.sort_values("similarity", ascending=False)
)

,Entreprise,Entreprise (Lieu Stage),similarity,similarity_percent
2290,FEMTO-ST / DÉPARTEMENT MÉCANIQUE APPLIQUÉE,FEMTO-ST / DÉPARTEMENT MÉCANIQUE APPLIQUÉE,1.000000,100.000000
2133,ARQUUS,ARQUUS,1.000000,100.000000
2282,FEMTO-ST,FEMTO-ST,1.000000,100.000000
119,ROBERT BOSCH GMBH,ROBERT BOSCH GMBH,1.000000,100.000000
122,SEGULA MATRA AUTOMOTIVE,SEGULA MATRA AUTOMOTIVE,1.000000,100.000000
...,...,...,...,...
1100,LORIA UMR 7503,UNIVERSITE D'AIX MARSEILLE,0.050000,5.000000
92,CTRE NAT DE LA RECHERCHE SCIENTIFIQUE,IPAG,0.048780,4.878049
18,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,FARMCUBE,0.028571,2.857143
1269,ONCF,EMIM,0.000000,0.000000
13,SERRU,AICM,0.000000,0.000000

In [25]:
print(f"Nombre de lignes comparées : {len(comparison)}")
print(f"Similarité moyenne : {comparison['similarity'].mean() * 100:.2f}%")
print(f"Médiane : {comparison['similarity'].median() * 100:.2f}%")

Nombre de lignes comparées : 537
Similarité moyenne : 59.59%
Médiane : 59.09%

In [26]:
print("≥ 90% :", (comparison["similarity"] >= 0.90).sum())
print("≥ 80% :", (comparison["similarity"] >= 0.80).sum())
print("≥ 70% :", (comparison["similarity"] >= 0.70).sum())

≥ 90% : 203
≥ 80% : 224
≥ 70% : 249

In [27]:
display(
    comparison[
        comparison["similarity"] < 0.70
    ].sort_values("similarity")
)

,Entreprise,Entreprise (Lieu Stage),similarity,similarity_percent
1269,ONCF,EMIM,0.000000,0.000000
13,SERRU,AICM,0.000000,0.000000
18,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,FARMCUBE,0.028571,2.857143
92,CTRE NAT DE LA RECHERCHE SCIENTIFIQUE,IPAG,0.048780,4.878049
1100,LORIA UMR 7503,UNIVERSITE D'AIX MARSEILLE,0.050000,5.000000
...,...,...,...,...
1008,RENAULT SAS,RENAULT CLEON,0.666667,66.666667
1637,UNIVERSITE DE POITIERS,UNIVERSITÉ DE POITIERS - INSTITUT PPRIME,0.677419,67.741935
1330,BOMBARDIER INC.,BOMBARDIER AEROSPACE,0.685714,68.571429
506,EXCENT FRANCE,EXCENT PUJAUDRAN,0.689655,68.965517
661,GOODYEAR DUNLOP TIRES FRANCE,GOODYEAR FRANCE,0.697674,69.767442

In [32]:
display(
    df[
        df["Ville (Lieu Stage)"].notna() &
        df["Pays (Lieu Stage)"].isna()
    ]
)

Empty DataFrame
Columns: [Année académique, N° Convention de stage, Date début, Date fin, Durée totale (mois), Type de Stage, Nature du stage, N° étudiant, NOM de l'élève, Prénom de l'élève, Entreprise, Titre du stage, Descriptif du Stage, Adresse, Code postal, Ville, Entreprise (Lieu Stage), CP (Lieu Stage), Ville (Lieu Stage), Pays (Lieu Stage), Date soutenance, Référent pédagogique (mail), Référent pédagogique (mail).1]
Index: []

In [31]:
count = (
    df["Ville (Lieu Stage)"].notna() &
    df["Pays (Lieu Stage)"].isna()
).sum()

print(f"Nombre de lignes : {count}")

Nombre de lignes : 0

In [36]:
pays_manuel = {
    6: "France",
    313: "France",
    1272: "France",
    1287: "France",
    1377: "France",
    1465: "France",
    1635: "France",
    1637: "France",
    1673: "Suède",
    1766: "France",
    1784: "Allemagne",
    1902: "France",
    1930: "France"
}

df.loc[pays_manuel.keys(), "Pays (Lieu Stage)"] = pd.Series(pays_manuel)

display(
    df.loc[
        pays_manuel.keys(),
        [
            "Entreprise (Lieu Stage)",
            "Ville (Lieu Stage)",
            "CP (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise (Lieu Stage),Ville (Lieu Stage),CP (Lieu Stage),Pays (Lieu Stage)
6,JET AVIATION,COLLONGES,74100,France
313,NaN,BESANCON,25000,France
1272,NaN,MERIGNAC,33700,France
1287,INSTITUT FEMTO-ST – DÉPARTEMENT MÉCANIQUE APPL...,BESANCON,25000,France
1377,FRANCECLAT,BESANCON CEDEX,25003,France
1465,INSTITUT NATIONAL DE L'ENVIRONNEMENT INDUSTRIE...,BOURGES,18000,France
1635,COMITE FRANCECLAT,BESANCON,25000,France
1637,UNIVERSITÉ DE POITIERS - INSTITUT PPRIME,POITIERS,86073,France
1673,ANGSTRÖMLABORIET,UPPSALA,752 00,Suède
1766,FEMTO-ST / DÉPARTEMENT AS2M,BESANCON,25030,France
1784,MTU AERO ENGINES AG,MUNICH,80995,Allemagne
1902,CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE,BESANCON,25000,France
1930,FEMTO-ST / DÉPARTEMENT MÉCANIQUE APPLIQUÉE,BESANCON CEDEX,25030,France

In [34]:
cp_manuel = {
    467: "BP 0000",     # Lomé, Togo — pas de CP classique fiable
    839: "330-0853",    # Saitama, Japon — approximation
    1166: "86000",      # Poitiers, France
    1272: "33700",      # Mérignac, France
    1383: "1400",       # Yverdon-les-Bains, Suisse
    1496: "050000",     # Hebei, Chine — approximation régionale
    1673: "752 00",     # Uppsala, Suède — approximation
    1684: "752 00",     # Uppsala, Suède — approximation
    1763: "434000",     # Jingzhou, Chine
    1835: "66000",      # Catalogne, Espagne — approximation
    1976: "434000",     # Jingzhou, Chine
    2000: "2926"        # Boncourt, Suisse
}

df.loc[cp_manuel.keys(), "CP (Lieu Stage)"] = pd.Series(cp_manuel)

display(
    df.loc[
        cp_manuel.keys(),
        [
            "Entreprise (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)",
            "CP (Lieu Stage)"
        ]
    ]
)

,Entreprise (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),CP (Lieu Stage)
467,AÉROPORT INTERNATIONAL GNASSINGBÉ EYADÉMA,LOMÉ,TOGO,BP 0000
839,TOKYO DENKI UNIVERSITY,SAITAMA,JAPON,330-0853
1166,SAFRAN ELECTRONICS & DEFENSE SAS,POITIERS,FRANCE,86000
1272,NaN,MERIGNAC,France,33700
1383,HEIG-VD,YVERDON-LES-BAINS,SUISSE,1400
1496,HBIS LAOTING STEEL CO LTD,HEBEI,CHINE,050000
1673,ANGSTRÖMLABORIET,UPPSALA,Suède,752 00
1684,ÅNGSTRÖMLABORATORIET,UPPSALA,SUEDE,752 00
1763,VALEO,JINGZHOU CITY,CHINE,434000
1835,NaN,CATALOGNE,ESPAGNE,66000
1976,"VALEO AUTOMOTIVE AIR CONDITIONING (HUBEI) CO.,...","JINGZHOU CITY, HUBEI PROVINCE",CHINE,434000
2000,SONCEBOZ MECHATRONICS BONCOURT SA,BONCOURT,SUISSE,2926

In [40]:
display(
    df.loc[
        df["Ville (Lieu Stage)"].isna() &
        (
            df["Entreprise (Lieu Stage)"].notna() |
            df["CP (Lieu Stage)"].notna() |
            df["Pays (Lieu Stage)"].notna()
        ),
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)
count = (
    df["Ville (Lieu Stage)"].isna() &
    (
        df["Entreprise (Lieu Stage)"].notna() |
        df["CP (Lieu Stage)"].notna() |
        df["Pays (Lieu Stage)"].notna()
    )
).sum()

print(f"Nombre de lignes : {count}")

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
14,NaN,NaN,NaN,BELGIQUE
17,NaN,NaN,NaN,SUISSE
24,NaN,NaN,NaN,DANEMARK
31,NaN,NaN,NaN,SUISSE
40,NaN,NaN,NaN,AUSTRALIE
...,...,...,...,...
1799,EIFFAGE NORGE NUF,3937,NaN,NORVEGE
2050,NaN,NaN,NaN,LUXEMBOURG
2241,NaN,75103,NaN,NaN
2249,NaN,NaN,NaN,FRANCE
2250,NaN,NaN,NaN,FRANCE

Nombre de lignes : 102

In [39]:
from pathlib import Path

OUTPUT_PATH = Path("../data/processed/stages_cleaned.xlsx")

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

df.to_excel(OUTPUT_PATH, index=False)

print(f"Fichier sauvegardé : {OUTPUT_PATH.resolve()}")

Fichier sauvegardé : C:\Users\LENOVO YOGA SLIM 6i\Desktop\rag-pfe-data\data\processed\stages_cleaned.xlsx

In [41]:
case_entreprise = (
    df["Entreprise (Lieu Stage)"].notna()
    & (
        df["CP (Lieu Stage)"].isna()
        | df["Ville (Lieu Stage)"].isna()
        | df["Pays (Lieu Stage)"].isna()
    )
)

print(f"Entreprise présente + information manquante : {case_entreprise.sum()}")

display(
    df.loc[
        case_entreprise,
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Entreprise présente + information manquante : 2

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
1124,IPEK-INSTITUT FÜR PRODUKTENTWICKLUNG,NaN,NaN,NaN
1799,EIFFAGE NORGE NUF,3937,NaN,NORVEGE

In [42]:
manual_location = {
    1124: {
        "CP (Lieu Stage)": "76131",
        "Ville (Lieu Stage)": "Karlsruhe",
        "Pays (Lieu Stage)": "ALLEMAGNE"
    },
    1799: {
        "Ville (Lieu Stage)": "Porsgrunn"
    }
}

for idx, values in manual_location.items():
    for column, value in values.items():
        df.loc[idx, column] = value

display(
    df.loc[
        manual_location.keys(),
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
1124,IPEK-INSTITUT FÜR PRODUKTENTWICKLUNG,76131,Karlsruhe,ALLEMAGNE
1799,EIFFAGE NORGE NUF,3937,Porsgrunn,NORVEGE

In [43]:
case_cp = (
    df["CP (Lieu Stage)"].notna()
    & (
        df["Ville (Lieu Stage)"].isna()
        | df["Pays (Lieu Stage)"].isna()
    )
)

print(f"CP présent + Ville/Pays manquant : {case_cp.sum()}")

display(
    df.loc[
        case_cp,
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

CP présent + Ville/Pays manquant : 2

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
726,NaN,70100,NaN,NaN
2241,NaN,75103,NaN,NaN

In [44]:
manual_location = {
    726: {
        "Ville (Lieu Stage)": "Gray",
        "Pays (Lieu Stage)": "FRANCE"
    },
    2241: {
        "Ville (Lieu Stage)": "Paris",
        "Pays (Lieu Stage)": "FRANCE"
    }
}

for idx, values in manual_location.items():
    for column, value in values.items():
        df.loc[idx, column] = value

display(
    df.loc[
        manual_location.keys(),
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
726,NaN,70100,Gray,FRANCE
2241,NaN,75103,Paris,FRANCE

In [47]:
display(df.loc[[726, 2241]])

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,Entreprise,Titre du stage,Descriptif du Stage,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
726,2021/2022,SIB - 2764 - 2021/2022,2022-04-04,2022-08-26,4.80,SIB,Stage en entreprise,2020091.0,FAYE,Bab,SIMU S.A.S,DEFINITION DES BESOINS ET EMPLACEMENT D’APPROV...,EMPLACEMENT POSTE DE CABLAGE -Lister les compo...,ZI DES GIRANAUX,70100,ARC LES GRAY,NaN,70100,Arc-lès-Gray,FRANCE,2022-10-27,nicolas.bodin@supmicrotech.fr,BODIN Nicolas
2241,2026/2027,SIA - 4466 - 2026/2027,2026-09-01,2027-01-31,5.07,SIA,NaN,2025170.0,MANGIN,Valentin,UPPSALA UNIVERSITET,X-RAY COMPUTED TOMOGRAPHY,Experimental investigation using x-ray compute...,LAGERHYDDSVAGEN 1,75103,UPPSALA,NaN,75103,Uppsala,SUÈDE,NaT,nicolas.martin@supmicrotech.fr,MARTIN Nicolas

In [46]:
manual_location = {
    726: {
        "Ville (Lieu Stage)": "Arc-lès-Gray",
        "Pays (Lieu Stage)": "FRANCE"
    },
    2241: {
        "Ville (Lieu Stage)": "Uppsala",
        "Pays (Lieu Stage)": "SUÈDE"
    }
}

for idx, values in manual_location.items():
    for column, value in values.items():
        df.loc[idx, column] = value

display(
    df.loc[
        manual_location.keys(),
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
726,NaN,70100,Arc-lès-Gray,FRANCE
2241,NaN,75103,Uppsala,SUÈDE

In [48]:
case_ville = (
    df["Ville (Lieu Stage)"].notna()
    & (
        df["CP (Lieu Stage)"].isna()
        | df["Pays (Lieu Stage)"].isna()
    )
)

print(f"Ville présente + CP/Pays manquant : {case_ville.sum()}")

display(
    df.loc[
        case_ville,
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Ville présente + CP/Pays manquant : 0

Empty DataFrame
Columns: [Entreprise (Lieu Stage), CP (Lieu Stage), Ville (Lieu Stage), Pays (Lieu Stage)]
Index: []

In [49]:
cols = [
    "Entreprise (Lieu Stage)",
    "CP (Lieu Stage)",
    "Ville (Lieu Stage)",
    "Pays (Lieu Stage)"
]

# Au moins une information renseignée
has_any = df[cols].notna().any(axis=1)

# Au moins une information manquante
has_missing = df[cols].isna().any(axis=1)

# Lignes concernées
location_incomplete = df[has_any & has_missing]

print(f"Nombre de lignes concernées : {len(location_incomplete)}")

display(
    location_incomplete[
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes concernées : 104

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
14,NaN,NaN,NaN,BELGIQUE
17,NaN,NaN,NaN,SUISSE
24,NaN,NaN,NaN,DANEMARK
31,NaN,NaN,NaN,SUISSE
40,NaN,NaN,NaN,AUSTRALIE
...,...,...,...,...
1835,NaN,66000,CATALOGNE,ESPAGNE
2050,NaN,NaN,NaN,LUXEMBOURG
2241,NaN,75103,Uppsala,SUÈDE
2249,NaN,NaN,NaN,FRANCE
2250,NaN,NaN,NaN,FRANCE

In [50]:
mask = (
    df["Entreprise (Lieu Stage)"].isna()
    & (
        df["CP (Lieu Stage)"].notna()
        | df["Ville (Lieu Stage)"].notna()
        | df["Pays (Lieu Stage)"].notna()
    )
)

print(f"Nombre de lignes trouvées : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes trouvées : 104

,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
14,NaN,NaN,NaN,BELGIQUE
17,NaN,NaN,NaN,SUISSE
24,NaN,NaN,NaN,DANEMARK
31,NaN,NaN,NaN,SUISSE
40,NaN,NaN,NaN,AUSTRALIE
...,...,...,...,...
1835,NaN,66000,CATALOGNE,ESPAGNE
2050,NaN,NaN,NaN,LUXEMBOURG
2241,NaN,75103,Uppsala,SUÈDE
2249,NaN,NaN,NaN,FRANCE
2250,NaN,NaN,NaN,FRANCE

In [51]:
mask = (
    df["Entreprise (Lieu Stage)"].notna()
    & (
        df["CP (Lieu Stage)"].isna()
        | df["Ville (Lieu Stage)"].isna()
        | df["Pays (Lieu Stage)"].isna()
    )
)

print(f"Nombre de lignes où l'entreprise existe mais au moins une info manque : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes où l'entreprise existe mais au moins une info manque : 0

Empty DataFrame
Columns: [Entreprise (Lieu Stage), CP (Lieu Stage), Ville (Lieu Stage), Pays (Lieu Stage)]
Index: []

In [53]:
mask = (
    df["Entreprise (Lieu Stage)"].isna()
    & df["Ville (Lieu Stage)"].notna()
    & df["CP (Lieu Stage)"].notna()
)

print(f"Nombre de lignes : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes : 6

,Entreprise,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
313,JESA SA,IMM NO. 5 - ZENITH MILLENIUM,20270,CASABLANCA,NaN,25000,BESANCON,France
489,ADHEX TECHNOLOGIES,POLNÁ 9,90301,SENEC,NaN,90301,SENEC,SLOVAQUIE
726,SIMU S.A.S,ZI DES GIRANAUX,70100,ARC LES GRAY,NaN,70100,Arc-lès-Gray,FRANCE
1272,THALES DMS FRANCE CAMPUS THALES BORDEAUX,75 AVENUE MARCEL DASSAULT,33700,MERIGNAC,NaN,33700,MERIGNAC,France
1835,NaN,ZA LES JALFRETTES,03500,SAINT-POURCAIN-SUR-SIOULE,NaN,66000,CATALOGNE,ESPAGNE
2241,UPPSALA UNIVERSITET,LAGERHYDDSVAGEN 1,75103,UPPSALA,NaN,75103,Uppsala,SUÈDE

In [54]:
manual_company = {
    726: "SIMU S.A.S",
    1272: "THALES DMS FRANCE CAMPUS THALES BORDEAUX",
    2241: "UPPSALA UNIVERSITET"
}

for idx, value in manual_company.items():
    df.loc[idx, "Entreprise (Lieu Stage)"] = value

display(
    df.loc[
        manual_company.keys(),
        [
            "Entreprise",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
726,SIMU S.A.S,SIMU S.A.S,70100,Arc-lès-Gray,FRANCE
1272,THALES DMS FRANCE CAMPUS THALES BORDEAUX,THALES DMS FRANCE CAMPUS THALES BORDEAUX,33700,MERIGNAC,France
2241,UPPSALA UNIVERSITET,UPPSALA UNIVERSITET,75103,Uppsala,SUÈDE

In [66]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean().mul(100),
}).sort_values("missing_count", ascending=False)
display(missing_summary)

                               missing_count  missing_percent
Entreprise (Lieu Stage)                 1747        76.221640
CP (Lieu Stage)                         1744        76.090750
Ville (Lieu Stage)                      1744        76.090750
Pays (Lieu Stage)                       1646        71.815009
Date soutenance                          704        30.715532
Nature du stage                          453        19.764398
Entreprise                                32         1.396161
Référent pédagogique (mail)               13         0.567190
Référent pédagogique (mail).1             13         0.567190
Descriptif du Stage                       12         0.523560
Date fin                                  12         0.523560
Date début                                11         0.479930
Année académique                           4         0.174520
Adresse                                    1         0.043630
N° Convention de stage                     0         0.000000
Type de Stage                              0         0.000000
Durée totale (mois)                        0         0.000000
Code postal                                0         0.000000
Prénom de l'élève                          0         0.000000
N° étudiant                                0         0.000000
Titre du stage                             0         0.000000
NOM de l'élève                             0         0.000000
Ville                                      0         0.000000

In [59]:
mask = df["Code postal"].isna()

print(f"Nombre de lignes : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes : 0

Empty DataFrame
Columns: [Entreprise, Adresse, Code postal, Ville, Entreprise (Lieu Stage), CP (Lieu Stage), Ville (Lieu Stage), Pays (Lieu Stage)]
Index: []

In [58]:
manual_cp = {
    467: "BP 0000",
    844: "32901",
    848: "SN15 1GD",
    1124: "76131",
    1591: "H1V 3N7"
}

for idx, value in manual_cp.items():
    df.loc[idx, "Code postal"] = value

display(
    df.loc[
        [467, 844, 848, 1124, 1591],
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

,Entreprise,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
467,"MINISTÈRE DES TRANSPORTS ROUTIERS, AÉRIENS ET ...",RUE ADAME,BP 0000,LOMÉ,AÉROPORT INTERNATIONAL GNASSINGBÉ EYADÉMA,BP 0000,LOMÉ,TOGO
844,FIT,150 WEST UNIVERSITY BOULEVARD,32901,MELBOURNE FL,NaN,NaN,NaN,NaN
848,DYMAG GROUP LTD,UNIT A/B BRUNEL PARK,SN15 1GD,CHIPPENHAM,NaN,NaN,NaN,NaN
1124,IPEK-INSTITUT FÜR PRODUKTENTWICKLUNG,GOTTHARD-FRANZ-STRAßE 9,76131,KARLSRUHE,IPEK-INSTITUT FÜR PRODUKTENTWICKLUNG,76131,Karlsruhe,ALLEMAGNE
1591,NaN,"4141 AV, PIERRE-DE COUBERTIN",H1V 3N7,MONTRÉAL,NaN,NaN,NaN,NaN

In [63]:
mask = df["Entreprise"].isna()

print(f"Nombre de lignes : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes : 32

,Entreprise,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
1,NaN,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN
3,NaN,8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN
4,NaN,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN
1529,NaN,"AV. MONOZUKURI 2 A, PARQUE INDUSTRIAL MARABIS",38200,COMONFORT,NaN,NaN,NaN,NaN
1537,NaN,150 W UNIVERSITY BLVD,FL 32901,MELBOURNE,NaN,NaN,NaN,NaN
1554,NaN,RUE DE SOLEURE 25,2740,MOUTIER,NaN,NaN,NaN,NaN
1591,NaN,"4141 AV, PIERRE-DE COUBERTIN",H1V 3N7,MONTRÉAL,NaN,NaN,NaN,NaN
1608,NaN,18 ALLÉE DU LASER,2301,LA CHAUX DE FONDS,NaN,NaN,NaN,NaN
1673,NaN,DIVISION OF BIOMEDICAL ENGINEERING,SE-751 03,UPPSALA,ANGSTRÖMLABORIET,752 00,UPPSALA,Suède
1736,NaN,SCHÜTZENGASSE 30,2540,GRANGES,NaN,NaN,NaN,NaN
1792,NaN,KAISERSTR. 10,76131,KARLSRUHE,INSTITUTE OF PRODUCT ENGINEERING AT KIT,76131,KARLSRUHE,ALLEMAGNE
1808,NaN,5 RUE DU BOIS DU LAN,1217,MEYRIN,NaN,NaN,NaN,NaN
1811,NaN,EDOUARD MICHELIN PLATZ 1,D- 66424,HOMBURG/ SAAR,NaN,NaN,NaN,NaN
1814,NaN,75FF+7R,33682,MIERES,NaN,NaN,NaN,NaN
1832,NaN,196 RUE DU MARÉCHAL JUIN,45200,AMILLY,NaN,NaN,NaN,NaN
1833,NaN,PARC DE LA FRINGALE,27101,VAL DE REUIL CEDEX,NaN,NaN,NaN,NaN
1834,NaN,ZAC DE L'AIRE DE VILLEROY,89150,FOUCHÈRES,NaN,NaN,NaN,NaN
1835,NaN,ZA LES JALFRETTES,03500,SAINT-POURCAIN-SUR-SIOULE,NaN,66000,CATALOGNE,ESPAGNE
1836,NaN,AVENUE DE LA CONCORDE,67120,ERNOLSHEIM-BRUCHE,NaN,NaN,NaN,NaN
1884,NaN,9 RUE THOMAS EDISON,25000,BESANÇON,NaN,NaN,NaN,NaN
1918,NaN,RUE DE LA JALUSE 6,2400,LE LOCLE,NaN,NaN,NaN,NaN
1941,NaN,54-56 AVENUE HOCHE,75008,PARIS,ELSYS DESIGN,38000,GRENOBLE,FRANCE
2174,NaN,22 BIS RUE DU CHÂTEAU GAILLARD,18320,BEFFES,NaN,NaN,NaN,NaN
2192,NaN,1100 NOTRE-DAME ST W,H3C 1K3,MONTRÉAL,NaN,NaN,NaN,NaN
2196,NaN,3 CALLE SAN FRANCISCO,33003,OVIEDO,CAMPUS DE VIESQUES,33203,GIJON,ESPAGNE
2199,NaN,150 W. UNIVERSITY BLVD,32901,MELBOURNE,NaN,NaN,NaN,NaN
2234,NaN,5-5 SENJUASAHICHO,120-8551,TOKYO,NaN,NaN,NaN,NaN
2247,NaN,GRAND RUE 12,1345,LE LIEU,NaN,NaN,NaN,NaN
2252,NaN,FABRIKSGATAN 2,57374,"YDRE, SWEDEN",NaN,NaN,NaN,NaN
2254,NaN,RUE A DEPONTHIÈRE 40,4431,LONCIN,NaN,NaN,NaN,NaN
2256,NaN,RUE MARYSE BASTIÉ,86100,CHÂTELLERAULT,SUPMICROTECH,25030,BESANCON,FRANCE
2258,NaN,UNIVERSITETSGATAN 2,SE-651 88,KARLSTAD,NaN,NaN,NaN,NaN

In [64]:
mask = df["Code postal"].astype(str).str.strip().eq("0")

print(f"Nombre de lignes : {mask.sum()}")

display(
    df.loc[
        mask,
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ]
)

Nombre de lignes : 1

,Entreprise,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
1,NaN,"6 BABBAGE WAY, EXETER, EX5 2FN",0,EXETER,NaN,NaN,NaN,NaN

In [65]:
df.loc[1, "Code postal"] = "EX5 2FN"

display(
    df.loc[
        1,
        [
            "Entreprise",
            "Adresse",
            "Code postal",
            "Ville",
            "Entreprise (Lieu Stage)",
            "CP (Lieu Stage)",
            "Ville (Lieu Stage)",
            "Pays (Lieu Stage)"
        ]
    ].to_frame().T
)

,Entreprise,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage)
1,NaN,"6 BABBAGE WAY, EXETER, EX5 2FN",EX5 2FN,EXETER,NaN,NaN,NaN,NaN

In [67]:
mask = df["Année académique"].isna()

print(f"Nombre de lignes : {mask.sum()}")

display(df.loc[mask])

Nombre de lignes : 4

,Année académique,N° Convention de stage,Date début,Date fin,Durée totale (mois),Type de Stage,Nature du stage,N° étudiant,NOM de l'élève,Prénom de l'élève,Entreprise,Titre du stage,Descriptif du Stage,Adresse,Code postal,Ville,Entreprise (Lieu Stage),CP (Lieu Stage),Ville (Lieu Stage),Pays (Lieu Stage),Date soutenance,Référent pédagogique (mail),Référent pédagogique (mail).1
1,NaN,SIA - 0 -,NaT,NaT,0.0,SIA,NaN,2025133.0,FEUILLET,Kerian,NaN,OPTICAL CHARACTERISATION AND ENVIRONMENTAL DUR...,The project concerns the optical properties of...,"6 BABBAGE WAY, EXETER, EX5 2FN",EX5 2FN,EXETER,NaN,NaN,NaN,NaN,NaT,sarah.bure@supmicrotech.fr,BURE Sarah
3,NaN,PFE - 0 -,NaT,NaT,0.0,PFE,NaN,2024195.0,PRIGENT,Capucine,NaN,STAGE SAV,"• Cartographier les processus SAV (réception, ...",8 RUE DE LA GOLISSE,1347,LE SENTIER,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,NaN,PFE - 4522 -,NaT,NaT,0.0,PFE,NaN,2024223.0,DEXEMPLE,Thibault,NaN,REVUE GLOBALE DE LA STRATÉGIE D'ASSURANCE QUAL...,-Réviser globalement la stratégie d’assurance ...,ROUTE DE LA GARE 70,2017,BOUDRY,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5,NaN,SIB - 0 -,NaT,NaT,0.0,SIB,NaN,2025212.0,VERET,Louis,FLORIDA INSTITUTE OF TECHNOLOGY,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...,Participation à un projet de recherche au sein...,150 WEST UNIVERSITY BOULEVARD,32901-6975,MELBOURNE,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [68]:
mask = df["Date début"] > df["Date fin"]

print("Date début > Date fin :", mask.sum())

display(
    df.loc[mask, [
        "Date début",
        "Date fin",
        "Durée totale (mois)",
        "Titre du stage"
    ]]
)

Date début > Date fin : 0

Empty DataFrame
Columns: [Date début, Date fin, Durée totale (mois), Titre du stage]
Index: []

In [69]:
display(
    df[
        (df["Date début"] < "2019-01-01") |
        (df["Date début"] > "2027-12-31")
    ][[
        "Date début",
        "Date fin",
        "Année académique",
        "Titre du stage"
    ]]
)

Empty DataFrame
Columns: [Date début, Date fin, Année académique, Titre du stage]
Index: []

In [70]:
display(
    df["Durée totale (mois)"]
    .value_counts(dropna=False)
    .sort_index()
)

Durée totale (mois)
0.00     12
0.03      1
0.07      2
0.10      3
0.13      2
         ..
12.03     3
12.07     1
12.13     1
12.17     2
13.13     1
Name: count, Length: 145, dtype: int64

In [71]:
display(
    df[
        (df["Durée totale (mois)"] <= 0) |
        (df["Durée totale (mois)"] > 24)
    ][[
        "Date début",
        "Date fin",
        "Durée totale (mois)",
        "Type de Stage",
        "Titre du stage"
    ]]
)

,Date début,Date fin,Durée totale (mois),Type de Stage,Titre du stage
1,NaT,NaT,0.0,SIA,OPTICAL CHARACTERISATION AND ENVIRONMENTAL DUR...
3,NaT,NaT,0.0,PFE,STAGE SAV
4,NaT,NaT,0.0,PFE,REVUE GLOBALE DE LA STRATÉGIE D'ASSURANCE QUAL...
5,NaT,NaT,0.0,SIB,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...
2192,NaT,NaT,0.0,SD,STAGE DE RECHERCHE - MÉTHODOLOGIES D'ÉTUDES DE...
2199,NaT,NaT,0.0,SIA,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...
2229,2026-08-24,NaT,0.0,SD,TRIBOLOGIE DU BOIS : RÉALISATION D’ESSAIS EXPÉ...
2243,NaT,NaT,0.0,SIA,SLOSH DAMPER FOR VIBRATION MITIGATION IN BUILD...
2249,NaT,NaT,0.0,SIA,AMORTISSEUR À MASSE OSCILLANTE POUR L'ATTÉNUAT...
2259,NaT,NaT,0.0,SIA,STAGE INGÉNIEUR MATÉRIAUX : CARACTÉRISATION ET...
2261,NaT,NaT,0.0,SIA,STAGE INGÉNIEUR MATÉRIAUX : CARACTÉRISATION ET...
2264,NaT,NaT,0.0,SIA,MODÉLISATION ET MESURES PHOTOMÉTRIQUES .

In [72]:
for col in [
    "Type de Stage",
    "Nature du stage",
    "Année académique"
]:
    print(f"\n===== {col} =====")
    display(df[col].value_counts(dropna=False))

===== Type de Stage =====

Type de Stage
PFE           963
SIB           562
SIA           530
MASTER         73
SNO            60
SD             51
PFE_MASTER     46
PFE_CPRO        7
Name: count, dtype: int64

===== Nature du stage =====

Nature du stage
Stage en entreprise                    1525
NaN                                     453
Stage en laboratoire                    243
Stage Plateforme SUPMICROTECH-ENSMM      52
Contrat de professionnalisation          18
Formation continue                        1
Name: count, dtype: int64

===== Année académique =====

Année académique
2023/2024    379
2022/2023    375
2021/2022    369
2020/2021    360
2025/2026    355
2024/2025    350
2026/2027    100
NaN            4
Name: count, dtype: int64

In [73]:
print("Nombre d'entreprises :", df["Entreprise"].nunique())

display(
    df["Entreprise"]
    .value_counts()
    .head(30)
)

Nombre d'entreprises : 1199

Entreprise
ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES MICROTECHNIQUES    91
FLORIDA INSTITUTE OF TECHNOLOGY                                   34
TOKYO DENKI UNIVERSITY                                            32
SCHRADER                                                          21
GRUPO ANTOLIN BESANCON                                            21
UNIVERSITE DE BESANCON                                            19
CTRE NAT DE LA RECHERCHE SCIENTIFIQUE                             19
COMUE UNIV BOURGOGNE FRANCHE COMTE                                18
COMMISSARIAT A ENERGIE ATOMIQUE                                   18
LOSANGE                                                           17
SONCEBOZ SA                                                       16
STATICE SAS                                                       14
STANLEY BLACK & DECKER MANUFACTURING SAS                          14
LOHR INDUSTRIE                                                    13
VOSGES TECHNOLOGIE INNOVATION & INDUSTRIE                         12
THALES AVIONICS SAS                                               12
FRAMATOME                                                         11
ELECTRICITE DE FRANCE                                             11
NAVAL GROUP                                                       11
SAFRAN AIRCRAFT ENGINES                                           11
KTH ROYAL INSTITUTE OF TECHNOLOGY                                 11
CISTEO MEDICAL                                                    10
PIXII                                                             10
UNIVERSITÉ MARIE ET LOUIS PASTEUR                                 10
SAFRAN ELECTRONICS & DEFENSE COCCKPIT SOLUTIONS                    9
BOUCLEDOR SA                                                       9
CHEVAL FRERES SOC                                                  9
JOHN DEERE SAS                                                     9
FAURECIA SIEGES D AUTOMOBILE                                       8
RENAULT SAS                                                        8
Name: count, dtype: int64

In [74]:
display(
    df["Entreprise"]
    .dropna()
    .sort_values()
    .to_frame()
)

                                             Entreprise
2006                                        202100-3120
325                                             2MATECH
266                                            4REALIZE
1881                                              A D R
600                                               A D R
...                                                 ...
477                                ÅNGSTRÖMLABORATORIET
2216  ÉCOLE DE TECHNOLOGIE SUPÉRIEURE (ÉTS) – LABORA...
1988               ÉCOLE SUPÉRIEURE SAINTE-ANNE DE PISE
1858  ÉTABLISSEMENT LOGISTIQUE DU COMMISSARIAT DES A...
2060                                          ÖSSUR EHF

[2260 rows x 1 columns]

In [75]:
company_counts = df["Entreprise"].value_counts()

print("Entreprises uniques :", df["Entreprise"].nunique())
print("Entreprises avec 1 seul stage :", (company_counts == 1).sum())
print("Entreprises avec 2 stages :", (company_counts == 2).sum())

Entreprises uniques : 1199
Entreprises avec 1 seul stage : 883
Entreprises avec 2 stages : 154

In [76]:
display(
    company_counts.value_counts()
    .sort_index()
)

count
1     883
2     154
3      59
4      32
5      14
6      10
7      10
8       9
9       4
10      3
11      5
12      2
13      1
14      2
16      1
17      1
18      2
19      2
21      2
32      1
34      1
91      1
Name: count, dtype: int64

In [77]:
display(
    df[
        df["Entreprise"]
        .astype("string")
        .str.contains("CEA|ENERGIE ATOMIQUE|ATOMIQUE", case=False, na=False)
    ]["Entreprise"].value_counts()
)

Entreprise
COMMISSARIAT A ENERGIE ATOMIQUE            18
MER OCEAN                                   2
CNOI (CHANTIER NAVAL DE L'OCEAN INDIEN)     1
Name: count, dtype: int64

In [78]:
import unicodedata

def normalize_company(name):
    if pd.isna(name):
        return None

    name = str(name).strip().upper()

    name = unicodedata.normalize("NFD", name)
    name = "".join(
        c for c in name
        if unicodedata.category(c) != "Mn"
    )

    name = " ".join(name.split())

    return name


company_check = df["Entreprise"].map(normalize_company)

print("Entreprises originales :", df["Entreprise"].nunique())
print("Entreprises après normalisation :", company_check.nunique())

Entreprises originales : 1199
Entreprises après normalisation : 1190

In [79]:
comparison = pd.DataFrame({
    "original": df["Entreprise"],
    "normalized": company_check
}).drop_duplicates()

display(
    comparison[
        comparison["original"].notna()
    ].sort_values("normalized")
)

                      original                normalized
2006               202100-3120               202100-3120
325                    2MATECH                   2MATECH
266                   4REALIZE                  4REALIZE
600                      A D R                     A D R
612      AB PROCESS INGENIERIE     AB PROCESS INGENIERIE
...                        ...                       ...
2139                  Z NAUTIC                  Z NAUTIC
1937      ZIMMER SURGICAL S.A.      ZIMMER SURGICAL S.A.
180   ZODIAC AERO DUCT SYSTEMS  ZODIAC AERO DUCT SYSTEMS
255          ZODIAC HYDRAULICS         ZODIAC HYDRAULICS
576             ZURFLUH FELLER            ZURFLUH FELLER

[1199 rows x 2 columns]

In [80]:
variants = (
    comparison
    .groupby("normalized")["original"]
    .nunique()
)

variants = variants[variants > 1]

print(
    f"Nombre de groupes avec plusieurs variantes : {len(variants)}"
)

Nombre de groupes avec plusieurs variantes : 9

In [81]:
display(
    comparison[
        comparison["normalized"].isin(variants.index)
    ].sort_values("normalized")
)

,original,normalized
2054,BIOMERIEUX SA,BIOMERIEUX SA
899,BIOMÉRIEUX SA,BIOMERIEUX SA
1221,DASSAULT SYSTEMES SE,DASSAULT SYSTEMES SE
1866,DASSAULT SYSTÈMES SE,DASSAULT SYSTEMES SE
1617,ETA SA MANUFACTURE HORLOGERE SUISSE,ETA SA MANUFACTURE HORLOGERE SUISSE
997,ETA SA MANUFACTURE HORLOGÈRE SUISSE,ETA SA MANUFACTURE HORLOGERE SUISSE
779,"G&F CHATELAIN, SUCCURSALE DE CHANEL SARL","G&F CHATELAIN, SUCCURSALE DE CHANEL SARL"
1278,"G&F CHÂTELAIN, SUCCURSALE DE CHANEL SARL","G&F CHATELAIN, SUCCURSALE DE CHANEL SARL"
978,HAUTE ÉCOLE D'INGÉNIERIE ET DE GESTION DU CANT...,HAUTE ECOLE D'INGENIERIE ET DE GESTION DU CANT...
386,HAUTE ECOLE D'INGÉNIERIE ET DE GESTION DU CANT...,HAUTE ECOLE D'INGENIERIE ET DE GESTION DU CANT...
1226,HEIG-VD HAUTE ECOLE D'INGÉNIERIE ET DE GESTION,HEIG-VD HAUTE ECOLE D'INGENIERIE ET DE GESTION
1240,HEIG-VD HAUTE ECOLE D'INGENIERIE ET DE GESTION,HEIG-VD HAUTE ECOLE D'INGENIERIE ET DE GESTION
433,"MANUFACTURE HORLOGÈRE VALFLEURIER, BRANCH OF R...","MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R..."
827,"MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...","MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R..."
712,UNIVERSITÉ DE FRANCHE COMTÉ,UNIVERSITE DE FRANCHE COMTE
1459,UNIVERSITE DE FRANCHE COMTE,UNIVERSITE DE FRANCHE COMTE
1010,USINES MÉTALLURGIQUES DE VALLORBE SA,USINES METALLURGIQUES DE VALLORBE SA
508,USINES METALLURGIQUES DE VALLORBE SA,USINES METALLURGIQUES DE VALLORBE SA

In [82]:
df["Entreprise"] = df["Entreprise"].map(normalize_company)

In [83]:
print("Entreprises uniques après normalisation :", df["Entreprise"].nunique())

display(
    df["Entreprise"]
    .value_counts()
    .head(30)
)

Entreprises uniques après normalisation : 1190

Entreprise
ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES MICROTECHNIQUES    91
FLORIDA INSTITUTE OF TECHNOLOGY                                   34
TOKYO DENKI UNIVERSITY                                            32
SCHRADER                                                          21
GRUPO ANTOLIN BESANCON                                            21
UNIVERSITE DE BESANCON                                            19
CTRE NAT DE LA RECHERCHE SCIENTIFIQUE                             19
COMUE UNIV BOURGOGNE FRANCHE COMTE                                18
COMMISSARIAT A ENERGIE ATOMIQUE                                   18
LOSANGE                                                           17
SONCEBOZ SA                                                       16
STATICE SAS                                                       14
STANLEY BLACK & DECKER MANUFACTURING SAS                          14
LOHR INDUSTRIE                                                    13
VOSGES TECHNOLOGIE INNOVATION & INDUSTRIE                         12
THALES AVIONICS SAS                                               12
FRAMATOME                                                         11
ELECTRICITE DE FRANCE                                             11
NAVAL GROUP                                                       11
SAFRAN AIRCRAFT ENGINES                                           11
KTH ROYAL INSTITUTE OF TECHNOLOGY                                 11
CISTEO MEDICAL                                                    10
PIXII                                                             10
UNIVERSITE MARIE ET LOUIS PASTEUR                                 10
SAFRAN ELECTRONICS & DEFENSE COCCKPIT SOLUTIONS                    9
BOUCLEDOR SA                                                       9
CHEVAL FRERES SOC                                                  9
JOHN DEERE SAS                                                     9
FAURECIA SIEGES D AUTOMOBILE                                       8
RENAULT SAS                                                        8
Name: count, dtype: int64

In [89]:
from rapidfuzz.fuzz import ratio

companies = (
    df["Entreprise"]
    .dropna()
    .drop_duplicates()
    .tolist()
)

similar_pairs = []

for i in range(len(companies)):
    for j in range(i + 1, len(companies)):
        score = ratio(companies[i], companies[j])

        if score >= 85:
            similar_pairs.append({
                "Entreprise 1": companies[i],
                "Entreprise 2": companies[j],
                "similarité": round(score, 2)
            })

similar_pairs = pd.DataFrame(similar_pairs)

display(
    similar_pairs
    .sort_values("similarité", ascending=False)
)

,Entreprise 1,Entreprise 2,similarité
14,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,99.27
52,"G&F CHATELAIN, SUCCURSALE DE CHANEL SARL","G&F CHATLAIN, SUCCURSALE DE CHANEL SARL",98.73
66,ETA SA MANUFACTURE HORLOGERE SUISSE,"ETA SA, MANUFACTURE HORLOGERE SUISSE",98.59
84,MANUFACTURE DES MONTRES ROLEX SA,MANUFACTURE DES MONTRES ROLEX SA.,98.46
63,MANUFACTURES CARTIER HORLOGERIE,MANUFACTURE CARTIER HORLOGERIE,98.36
...,...,...,...
39,"MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...",MANUFACTURE CARTIER JOAILLERIE BRANCH OF RICHE...,85.51
13,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","MANUFACTURE ROGER DUBUIS, BRANCH OF RICHEMONT ...",85.50
9,MANUFACTURE CARTIER JOAILLERIE,MANUFACTURES CARTIER HORLOGERIE,85.25
35,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,85.07
58,MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",85.00

In [90]:
candidates = similar_pairs[
    similar_pairs["similarité"] >= 95
].copy()

display(
    candidates.sort_values(
        "similarité",
        ascending=False
    )
)

,Entreprise 1,Entreprise 2,similarité
14,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,99.27
52,"G&F CHATELAIN, SUCCURSALE DE CHANEL SARL","G&F CHATLAIN, SUCCURSALE DE CHANEL SARL",98.73
66,ETA SA MANUFACTURE HORLOGERE SUISSE,"ETA SA, MANUFACTURE HORLOGERE SUISSE",98.59
84,MANUFACTURE DES MONTRES ROLEX SA,MANUFACTURE DES MONTRES ROLEX SA.,98.46
3,FLORIDA INSTITUTE OF TECHNOLOGY,FLORIDA INSTITUE OF TECHNOLOGY,98.36
63,MANUFACTURES CARTIER HORLOGERIE,MANUFACTURE CARTIER HORLOGERIE,98.36
30,LIEBHERR MACHINES BULLES SA,LIEBHERR MACHINES BULLE SA,98.11
91,"VALEO AUTOMATIVE AIR CONDITIONING (HUBEI) CO, LTD",VALEO AUTOMATIVE AIR CONDITIONNING (HUBEI) CO LTD,97.96
37,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...","MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",97.67
73,CHH MICROTECHNIQUE SA,CHH MICROTECHNIQUE SA.,97.67
83,AUDEMARS PIGUET SA,AUDEMARS PIGUET SA.,97.30
87,"VALEO AUTOMOTIVE AIR CONDITIONING (HUBEI) CO.,...","VALEO AUTOMATIVE AIR CONDITIONING (HUBEI) CO, LTD",96.97
89,"VALEO AUTOMOTIVE AIR CONDITIONING (HUBEI) CO.,...","VALEO AUTOMOTIVE AIR CONDITIONING HUBEI CO.,LTD",96.91
20,KERI MEDICAL SA,KERIMEDICAL SA,96.55
96,ORANO PROJETS,ORANO PROJET,96.00
42,USINES METALLURGIQUES DE VALLORBE SA,USINES METALLURGIQUES DE VALLORBE,95.65
45,JETAVIATION,JET AVIATION,95.65
72,BULGARI HORLOGERIE SA,BVLGARI HORLOGERIE SA,95.24

In [86]:
import re

def normalize_company(name):
    if pd.isna(name):
        return None

    name = str(name).strip().upper()

    # Accents
    name = unicodedata.normalize("NFD", name)
    name = "".join(
        c for c in name
        if unicodedata.category(c) != "Mn"
    )

    # Apostrophes typographiques
    name = name.replace("’", "'")

    # S.A., S.A → SA
    name = re.sub(r"\bS\.A\.?\b", "SA", name)

    # Ponctuation autour des espaces
    name = re.sub(r"\s*-\s*", " ", name)

    # Espaces multiples
    name = re.sub(r"\s+", " ", name)

    return name.strip()

In [87]:
df["Entreprise"] = df["Entreprise"].map(normalize_company)

In [88]:
companies = (
    df["Entreprise"]
    .dropna()
    .drop_duplicates()
    .tolist()
)

print("Nombre d'entreprises :", len(companies))

Nombre d'entreprises : 1183

In [91]:
# Garder les paires avec une similarité >= 95 %
high_similarity = similar_pairs[
    similar_pairs["similarité"] >= 95
].copy()

# ============================================================
# Regroupement des variantes
# ============================================================

parent = {}

def find(x):
    if parent[x] != x:
        parent[x] = find(parent[x])
    return parent[x]

def union(a, b):
    if a not in parent:
        parent[a] = a
    if b not in parent:
        parent[b] = b

    root_a = find(a)
    root_b = find(b)

    if root_a != root_b:
        parent[root_b] = root_a


# Construire les groupes de similarité
for _, row in high_similarity.iterrows():
    union(row["Entreprise 1"], row["Entreprise 2"])


# Créer le mapping
groups = {}

for company in parent:
    root = find(company)
    groups.setdefault(root, []).append(company)

company_mapping = {}

for root, companies in groups.items():
    reference = companies[0]

    for company in companies:
        company_mapping[company] = reference


# Appliquer la fusion directement dans la colonne Entreprise
df["Entreprise"] = df["Entreprise"].replace(company_mapping)

print("Nombre d'entreprises :", df["Entreprise"].nunique())

Nombre d'entreprises : 1165

In [92]:
similar_90_95 = similar_pairs[
    (similar_pairs["similarité"] >= 90) &
    (similar_pairs["similarité"] < 95)
].copy()

display(
    similar_90_95.sort_values(
        "similarité",
        ascending=False
    )
)

,Entreprise 1,Entreprise 2,similarité
88,"VALEO AUTOMOTIVE AIR CONDITIONING (HUBEI) CO.,...",VALEO AUTOMATIVE AIR CONDITIONNING (HUBEI) CO LTD,94.95
51,SAFRAN AERO BOOSTERS,SAFRAN AEROBOOSTER,94.74
7,C & K COMPONENTS SAS,C&K COMPONENTS SAS,94.74
48,MANUFACTURE LA JOUX PERRET,MANUFACTURE LA JOUX PERRET SA,94.55
59,THE UNIVERSITY OF ADELAIDE SA,THE UNIVERSITY OF ADELAIDE,94.55
43,DUBOIS & DEPRAZ SA,DUBOIS DEPRAZ SA,94.12
81,SONCEBOZ MOTION BONCOURT SA,SONCEBOZ MOTION BONCOURT,94.12
62,MANUFACTURES CARTIER HORLOGERIE,"MANUFACTURES CARTIER HORLOGERIE, SA",93.94
5,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,ECOLE NATIONALE SUPERIEURE DE MECANIQUE ET DES...,93.94
92,"VALEO AUTOMATIVE AIR CONDITIONING (HUBEI) CO, LTD","VALEO AUTOMOTIVE AIR CONDITIONING HUBEI CO.,LTD",93.75
25,SOC DES ATELIERS LOUIS VUITTON,SOCIETE DES ATELIERS LOUIS VUITTON,93.75
46,AZUREA TECHNOLOGIE HORLOGERE SA,AZUREA TECHNOLOGIES HORLOGERE,93.33
55,SAFRAN ELECTRONICS & DEFENSE,SAFRAN ELECTRONICS AND DEFENSE,93.10
27,UNIVERSITE DE FRANCHE COMTE,UFC UNIVERSITE DE FRANCHE COMTE,93.10
47,BNOVATE TECHNOLOGIES SA,BNOVATE TECHNOLOGIES,93.02
69,THIRODE GRANDES CUISINES POLIGNY,THIRODE GRANDES CUISINES POLIGNY TGCP,92.75
75,"MANUFACTURES CARTIER HORLOGERIE, SA",MANUFACTURE CARTIER HORLOGERIE,92.31
90,BAUD TECHNOLOGY SOLUTION,BAUD TECHNOLOGY SOLUTIONS SA,92.31
76,BVLGARI HORLOGERIE,BVLGARI HORLOGERIE SA,92.31
23,MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET & CIE,MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET SA,92.13
17,SEGULA MATRA AUTOMOTIVE,SEGULA MATRA AUTOMOTIVE SAS,92.00
32,UPPSALA UNIVERSITY,UPPSALA UNIVERSITET,91.89
74,UNIVERSITY OF BRUNEL,UNIVERSITY BRUNEL,91.89
6,UNIVERSITE DE GENEVE,UNIVERSITE GENEVE,91.89
57,MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,MANUFACTURE CARTIER JOAILLERIE BRANCH OF RICHE...,91.85
95,VALEO AUTOMATIVE AIR CONDITIONNING (HUBEI) CO LTD,"VALEO AUTOMOTIVE AIR CONDITIONING HUBEI CO.,LTD",91.67
94,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO (UFRJ),UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,91.57
28,BIEN AIR SURGERY SA,BIEN AIR SURGERY,91.43
1,FLORIDA INSTITUTE OF TECHNOLOGY,FLORIDA INSTITUTE OF TECHNOLOGY (FIT),91.18
15,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",MANUFACTURE CARTIER JOAILLERIE BRANCH OF RICHE...,91.18
36,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...","MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",91.06
93,EFBE PRUFTECHNIK,EFBE PRUFTECHNICS,90.91
31,BAUD INDUSTRIES,SA BAUD INDUSTRIES,90.91
67,SOCIETE DES ATELIERS LOUIS VUITTON,SOCIETE DES ATELIERS LOUIS VUITTON (SALV),90.67
26,THALES LAS FRANCE SAS,THALES DMS FRANCE SAS,90.48
77,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...","MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",90.00
78,KARLSTAD UNIVERSITY,KARLSTADS UNIVERSITET,90.00

In [93]:
# ============================================================
# FUSION DES ENTREPRISES SIMILAIRES ENTRE 90 % ET 95 %
# ============================================================

# Paires entre 90 % et 95 %
similar_90_95 = similar_pairs[
    (similar_pairs["similarité"] >= 90) &
    (similar_pairs["similarité"] < 95)
].copy()

# Cas à NE PAS fusionner
excluded_pairs = {
    (
        "THALES LAS FRANCE SAS",
        "THALES DMS FRANCE SAS"
    ),
    (
        "MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET & CIE",
        "MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET SA"
    )
}

# ============================================================
# Union-Find
# ============================================================

parent = {}

def find(x):
    if parent[x] != x:
        parent[x] = find(parent[x])
    return parent[x]

def union(a, b):
    if a not in parent:
        parent[a] = a
    if b not in parent:
        parent[b] = b

    root_a = find(a)
    root_b = find(b)

    if root_a != root_b:
        parent[root_b] = root_a


# Construire les groupes
for _, row in similar_90_95.iterrows():

    pair = (
        row["Entreprise 1"],
        row["Entreprise 2"]
    )

    # Vérifier aussi l'ordre inverse
    reverse_pair = (
        row["Entreprise 2"],
        row["Entreprise 1"]
    )

    if pair in excluded_pairs or reverse_pair in excluded_pairs:
        continue

    union(
        row["Entreprise 1"],
        row["Entreprise 2"]
    )


# ============================================================
# Créer le mapping
# ============================================================

groups = {}

for company in parent:
    root = find(company)
    groups.setdefault(root, []).append(company)

company_mapping = {}

for root, companies in groups.items():
    reference = companies[0]

    for company in companies:
        company_mapping[company] = reference


# ============================================================
# Appliquer la fusion
# ============================================================

df["Entreprise"] = df["Entreprise"].replace(company_mapping)

print("Nombre d'entreprises :", df["Entreprise"].nunique())

Nombre d'entreprises : 1137

In [94]:
similar_85_90 = similar_pairs[
    (similar_pairs["similarité"] >= 85) &
    (similar_pairs["similarité"] < 90)
].copy()

display(
    similar_85_90.sort_values(
        "similarité",
        ascending=False
    )
)

print("Nombre de paires entre 85 % et 90 % :", len(similar_85_90))

,Entreprise 1,Entreprise 2,similarité
61,THE UNIVERSITY OF ELECTRO COMMUNICATIONS,THE UNIVERSITY OF ELECTRO COMMUNICATIONS (??????),89.89
0,FLORIDA INSTITUTE OF TECHNOLOGY,FIT (FLORIDA INSITUTE OF TECHNOLOGY),89.55
85,FLORIDA INSTITUTE OF TECHNOLOGY (FIT),FLORIDA INSTITUE OF TECHNOLOGY,89.55
65,OFF NAT ETUDES RECHERCHES AEROSPATIALE,OFF NAT ETUDES RECHERCHES AEROSPATIALES (ONERA),89.41
2,FLORIDA INSTITUTE OF TECHNOLOGY,FLORIDA INSTITUTE OF TECH,89.29
79,INSTITUT NATIONAL DE RECHERCHE ET DE SECURITE,INSTITUT NATIONAL RECHERCHE SECURITE,88.89
22,"OFFICINE PANERAI, BRANCH OF RICHEMONT INTERNAT...","OFFICINE PANERAI, BRANCH OF RICHEMONT INT. SA",88.89
68,CARAN D'ACHE SA,CARAN D'ACHE,88.89
21,KERI MEDICAL SA,KERI MEDICAL,88.89
53,JET AVIATION,JET AVIATION AG,88.89
86,LUXURY TRAINS SERVIZI SRL,LUXURY TRAIN SERVIZI,88.89
80,ELECTRO MEDICAL SYSTEMS SA.,E.M.S. ELECTRO MEDICAL SYSTEMS SA.,88.52
24,ALSTOM TRANSPORT SA,ALSTOM TRANSPORT SA (93),88.37
44,HYDRO BUILDING SYSTEMS FRANCE,HYDRO BUILDING SYSTEMS GERMANY,88.14
64,VALFLEURIER,VALFLEURIER SA,88.00
54,TOKYO DENKI UNIVERSITY,TOKYO DENKI UNIVERSITY (TDU),88.00
41,FM INDUSTRIES,FH INDUSTRIE,88.00
60,FIT (FLORIDA INSITUTE OF TECHNOLOGY),FLORIDA INSTITUE OF TECHNOLOGY,87.88
49,HERMES SELLIER,HERMES SELLIER SAS,87.50
98,FLORIDA INSTITUTE OF TECH,FLORIDA INSTITUE OF TECHNOLOGY,87.27
38,"MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...","MANUFACTURE ROGER DUBUIS, BRANCH OF RICHEMONT ...",87.22
71,BULGARI HORLOGERIE SA,BVLGARI HORLOGERIE,87.18
29,"PIAGET, BRANCH OF RICHEMONT INTERNATIONAL SA","PROCADRANS, BRANCH OF RICHEMONT INTERNATIONAL SA",86.96
50,SAFRAN AIRCRAFT ENGINES,SAFRAN AIRCRAFT ENGINES POLAND,86.79
82,GE HEALTHCARE,GE HEALTHCARE SAS,86.67
10,MANUFACTURE CARTIER JOAILLERIE,MANUFACTURE CARTIER HORLOGERIE,86.67
56,EFBE PRUFTECHNIK GMBH,EFBE PRUFTECHNIK,86.49
97,SEGULA TECHNOLOGIES FRANCE,SEGULA TECHNOLOGIES MATRA,86.27
33,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...","MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...",86.13
16,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",85.95
34,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...","MANUFACTURE ROGER DUBUIS, BRANCH OF RICHEMONT ...",85.94
11,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",85.93
12,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...",85.71
8,DECATHLON,DECATHLON SE,85.71
4,JET AVIATION AGBASEL,JET AVIATION AG,85.71
19,BOUCLEDOR SA,BOUCLEDOR,85.71
70,ATLAS MICROTECH,ATLAS MICROTECH SARL,85.71
40,FM INDUSTRIES,FEMSO INDUSTRIE,85.71
18,TAG HEUER,TAG HEUER SA,85.71
39,"MANUFACTURE HORLOGERE VALFLEURIER, BRANCH OF R...",MANUFACTURE CARTIER JOAILLERIE BRANCH OF RICHE...,85.51
13,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","MANUFACTURE ROGER DUBUIS, BRANCH OF RICHEMONT ...",85.50
9,MANUFACTURE CARTIER JOAILLERIE,MANUFACTURES CARTIER HORLOGERIE,85.25
35,"MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,85.07
58,MANUFACTURES CARTIER HORLOGERIE BRANCH OF RICH...,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...",85.00

Nombre de paires entre 85 % et 90 % : 44

In [95]:
# ============================================================
# FUSION DES VARIANTES 85 % - 90 %
# ============================================================

company_replacements = {

    # 1. The University of Electro-Communications
    "THE UNIVERSITY OF ELECTRO COMMUNICATIONS (??????)":
        "THE UNIVERSITY OF ELECTRO COMMUNICATIONS",

    # 2. Florida Institute of Technology
    "FIT (FLORIDA INSITUTE OF TECHNOLOGY)":
        "FLORIDA INSTITUTE OF TECHNOLOGY",

    "FLORIDA INSTITUTE OF TECH":
        "FLORIDA INSTITUTE OF TECHNOLOGY",

    "FLORIDA INSTITUE OF TECHNOLOGY":
        "FLORIDA INSTITUTE OF TECHNOLOGY",

    "FLORIDA INSTITUTE OF TECHNOLOGY (FIT)":
        "FLORIDA INSTITUTE OF TECHNOLOGY",

    # 3. ONERA
    "OFF NAT ETUDES RECHERCHES AEROSPATIALES (ONERA)":
        "OFF NAT ETUDES RECHERCHES AEROSPATIALE",

    # 4. Institut National de Recherche et de Sécurité
    "INSTITUT NATIONAL RECHERCHE SECURITE":
        "INSTITUT NATIONAL DE RECHERCHE ET DE SECURITE",

    # 5. Officine Panerai
    "OFFICINE PANERAI, BRANCH OF RICHEMONT INT. SA":
        "OFFICINE PANERAI, BRANCH OF RICHEMONT INTERNATIONAL SA",

    # 6. Caran d'Ache
    "CARAN D'ACHE":
        "CARAN D'ACHE SA",

    # 7. Keri Medical
    "KERI MEDICAL":
        "KERI MEDICAL SA",

    # 8. Jet Aviation
    "JET AVIATION AG":
        "JET AVIATION",

    # 9. Luxury Trains
    "LUXURY TRAIN SERVIZI":
        "LUXURY TRAINS SERVIZI SRL",

    # 10. Electro Medical Systems
    "E.M.S. ELECTRO MEDICAL SYSTEMS SA.":
        "ELECTRO MEDICAL SYSTEMS SA.",

    # 11. Alstom
    "ALSTOM TRANSPORT SA (93)":
        "ALSTOM TRANSPORT SA",

    # 12. Valfleurier
    "VALFLEURIER SA":
        "VALFLEURIER",

    # 13. Tokyo Denki University
    "TOKYO DENKI UNIVERSITY (TDU)":
        "TOKYO DENKI UNIVERSITY",

    # 14. Hermes Sellier
    "HERMES SELLIER SAS":
        "HERMES SELLIER",

    # 15. GE Healthcare
    "GE HEALTHCARE SAS":
        "GE HEALTHCARE",

    # 16. EFBE
    "EFBE PRUFTECHNIK GMBH":
        "EFBE PRUFTECHNIK",

    # 17. Decathlon
    "DECATHLON SE":
        "DECATHLON",

    # 18. Jet Aviation AG Basel
    "JET AVIATION AGBASEL":
        "JET AVIATION",

    # 19. Boucledor
    "BOUCLEDOR":
        "BOUCLEDOR SA",

    # 20. Atlas Microtech
    "ATLAS MICROTECH SARL":
        "ATLAS MICROTECH",

    # 21. TAG Heuer
    "TAG HEUER SA":
        "TAG HEUER",
}


# Appliquer uniquement les remplacements définis ci-dessus
df["Entreprise"] = df["Entreprise"].replace(company_replacements)


# Vérification
print("Nombre d'entreprises :", df["Entreprise"].nunique())

Nombre d'entreprises : 1116

In [98]:
similar_pairs_80_85 = similar_pairs_70_85[
    (similar_pairs_70_85["similarité"] >= 80) &
    (similar_pairs_70_85["similarité"] < 85)
].copy()

display(
    similar_pairs_80_85
    .sort_values("similarité", ascending=False)
    .reset_index(drop=True)
)

,Entreprise 1,Entreprise 2,similarité
0,LOHR INDUSTRIE,FH INDUSTRIE,84.62
1,FM INDUSTRIES,MBK INDUSTRIE,84.62
2,"KOMATSUSEIKI KOSAKUSHO CO.,LTD",KOMATSUSEIKI KOSAKUSHO,84.62
3,GE HEALTHCARE,BA HEALTHCARE,84.62
4,KOMATSUSEIKI KOSAKUSHO COMPANY,KOMATSUSEIKI KOSAKUSHO,84.62
5,THALES ALENIA SPACE FRANCE,THALES ALENIA SPACE,84.44
6,"OFFICINE PANERAI, BRANCH OF RICHEMONT INTERNAT...","PROCADRANS, BRANCH OF RICHEMONT INTERNATIONAL SA",84.31
7,CEDRAT TECHNOLOGIES,BERTIN TECHNOLOGIES,84.21
8,BERTIN TECHNOLOGIES,CEPRIM TECHNOLOGIES,84.21
9,CEDRAT TECHNOLOGIES,CEPRIM TECHNOLOGIES,84.21
10,BONINCHI SA,BONINCHI,84.21
11,"OFFICINE PANERAI, BRANCH OF RICHEMONT INTERNAT...","PIAGET, BRANCH OF RICHEMONT INTERNATIONAL SA",83.67
12,WS INDUSTRIE,FH INDUSTRIE,83.33
13,KOMATSUSEIKI KOSAKUSHO COMPANY,"KOMATSUSEIKI KOSAKUSHO CO.,LTD",83.33
14,GOODYEAR DUNLOP TIRES OPERATIONS,GOODYEAR DUNLOP TIRES FRANCE,83.33
15,SONCEBOZ MECHATRONICS BONCOURT SA,SONCEBOZ MOTION BONCOURT SA,83.33
16,SANOFI WINTHROP INDUSTRIES,SANOFI WINTHROP INDUSTRIE LE TRAIT,83.33
17,BRUNEL UNIVERSITY,BRUNEL UNIVERSITY LONDON,82.93
18,THALES DMS FRANCE SAS,THALES SIX GTS FRANCE SAS,82.61
19,THALES LAS FRANCE SAS,THALES SIX GTS FRANCE SAS,82.61
20,KERI MEDICAL SA,KERI MEDICAL FRANCE,82.35
21,MANUFACTURE HORLOGERE VALFLEURIER,MANUFACTURE VALFLEURIER,82.14
22,ANSYS FRANCE,SGS FRANCE,81.82
23,FRAMATOME,FRAMATOME ARC,81.82
24,UNIVERSITE DE LORRAINE,UNIVERSITE DE LAUSANNE,81.82
25,UNIVERSITE DE BESANCON,UNIVERSITE DE LAUSANNE,81.82
26,FEMSO INDUSTRIE,FH INDUSTRIE,81.48
27,WS INDUSTRIE,FEMSO INDUSTRIE,81.48
28,ASSYSTEM FRANCE,ANSYS FRANCE,81.48
29,ARIANE GROUP,ARIANEGROUP SAS,81.48
30,FLORIDA INSTITUTE OF TECHNOLOGY,KTH ROYAL INSTITUTE OF TECHNOLOGY,81.25
31,BRUNEL UNIVERSITY,LUND UNIVERSITY,81.25
32,BAUD INDUSTRIES,BAUD INDUSTRIES SUISSE,81.08
33,UNIVERSITE DE NANTES,UNIVERSITE DE LAUSANNE,80.95
34,UNIVERSITE DE MONTREAL,UNIVERSITE DE NANTES,80.95
35,UNIVERSITE DE NANTES,UNIVERSITE DE POITIERS,80.95
36,UNIVERSITE DE LORRAINE,UNIVERSITE DE TOULON,80.95
37,UNIVERSITE DE LORRAINE,UNIVERSITE DE NANTES,80.95
38,SAFRAN LANDING SYSTEMS,SAFRAN FILTRATION SYSTEMS,80.85
39,SAFRAN TRANSMISSION SYSTEMS,SAFRAN FILTRATION SYSTEMS,80.77
40,"PROCADRANS, BRANCH OF RICHEMONT INTERNATIONAL SA","VAN CLEEF & ARPELS, BRANCH OF RICHEMONT INTERN...",80.77
41,SONCEBOZ MICROTECHNIQUE BONCOURT SA,SONCEBOZ MOTION BONCOURT SA,80.65
42,MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET SA,"MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET SA, S...",80.37
43,"MANUFACTURES CARTIER HORLOGERIE, BRANCH OF RIC...","CAMPUS GENEVOIS DE HAUTE HORLOGERIE, BRANCH OF...",80.28
44,"PIAGET, BRANCH OF RICHEMONT INTERNATIONAL SA","VAN CLEEF & ARPELS, BRANCH OF RICHEMONT INTERN...",80.00
45,SKF FRANCE,SGS FRANCE,80.00
46,MOVING MAGNET TECHNOLOGIES,PONANT TECHNOLOGIES,80.00
47,MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET & CIE,"MANUFACTURE D'HORLOGERIE AUDEMARS PIGUET SA, S...",80.00
48,UNIVERSITE DE GENEVE,UNIVERSITE DE NANTES,80.00
49,PIXEE MEDICAL,DIXI MEDICAL,80.00
50,WS INDUSTRIE,MBK INDUSTRIE,80.00
51,WS INDUSTRIE,FM INDUSTRIES,80.00
52,LATESYS,ARTHESYS,80.00
53,MBK INDUSTRIE,FH INDUSTRIE,80.00
54,SINGER SA,SPINEART SA,80.00
55,R.MONTAVON SA,REMY MONTAVON SA.,80.00
56,PARALEC ENERGY,PARALEC ENERGY CO LTD,80.00
57,UNIVERSITY OF CANTERBURY,UNIVERSITY OF MARIBOR,80.00

In [99]:
company_replacements_80_85 = {
    "KOMATSUSEIKI KOSAKUSHO CO.,LTD": "KOMATSUSEIKI KOSAKUSHO",
    "KOMATSUSEIKI KOSAKUSHO COMPANY": "KOMATSUSEIKI KOSAKUSHO",

    "THALES ALENIA SPACE FRANCE": "THALES ALENIA SPACE",

    "BONINCHI SA": "BONINCHI",

    "BRUNEL UNIVERSITY LONDON": "BRUNEL UNIVERSITY",

    "MANUFACTURE HORLOGERE VALFLEURIER": "MANUFACTURE VALFLEURIER",

    "ARIANEGROUP SAS": "ARIANE GROUP",

    "BAUD INDUSTRIES SUISSE": "BAUD INDUSTRIES",

    "R.MONTAVON SA": "REMY MONTAVON SA.",

    "PARALEC ENERGY CO LTD": "PARALEC ENERGY",
}

df["Entreprise"] = df["Entreprise"].replace(company_replacements_80_85)

print("Nombre d'entreprises :", df["Entreprise"].nunique())

Nombre d'entreprises : 1106

In [104]:
similar_pairs_75_77 = similar_pairs_70_85[
    (similar_pairs_70_85["similarité"] >= 76) &
    (similar_pairs_70_85["similarité"] < 77)
].copy()

display(
    similar_pairs_75_77
    .sort_values("similarité", ascending=False)
    .reset_index(drop=True)
)

,Entreprise 1,Entreprise 2,similarité
0,LOHR INDUSTRIE,WS INDUSTRIE,76.92
1,EXCENT FRANCE,EXPLEO FRANCE,76.92
2,UNIVERSITE,UNIVERSITE LAVAL,76.92
3,EXPLEO FRANCE,NESTLE FRANCE,76.92
4,ORANGE,LOSANGE,76.92
5,INOMED,CANOMED,76.92
6,UNIVERSITE DE FRANCHE COMTE,UNIVERSITE DE NANTES,76.60
7,BNOVATE TECHNOLOGIES SA,COMPPAIR TECHNOLOGIES SA,76.60
8,LUND UNIVERSITY,LINNAEUS UNIVERSITY,76.47
9,BSN MEDICAL SAS,B. BRAUN MEDICAL SA,76.47
10,LUND UNIVERSITY,KARLSTAD UNIVERSITY,76.47
11,LOHR INDUSTRIE,TRELLEBORG INDUSTRIE,76.47
12,"PIAGET, BRANCH OF RICHEMONT INTERNATIONAL SA","MANUFACTURE JAEGER LECOULTRE, BRANCH OF RICHEM...",76.36
13,"MANUFACTURE ROGER DUBUIS, BRANCH OF RICHEMONT ...","PROCADRANS, BRANCH OF RICHEMONT INTERNATIONAL SA",76.36
14,UNIVERSITE DE BESANCON,UNIVERSITE DE GENEVE,76.19
15,VIROBOTIC,CIS ROBOTICS,76.19
16,CEDRAT TECHNOLOGIES,BLANC AERO TECHNOLOGIES,76.19
17,UNIVERSITE DE BESANCON,UNIVERSITE DE NANTES,76.19
18,UNIVERSITE DE BESANCON,UNIVERSITE DE TOULON,76.19
19,UNIVERSITE DE GENEVE,UNIVERSITE DE LORRAINE,76.19
20,UNIVERSITE DE GENEVE,UNIVERSITE DE MONTREAL,76.19
21,UNIVERSITE DE GENEVE,UNIVERSITE DE LAUSANNE,76.19
22,BLANC AERO TECHNOLOGIES,BERTIN TECHNOLOGIES,76.19
23,BNOVATE TECHNOLOGIES SA,PONANT TECHNOLOGIES,76.19
24,ALTRAN TECHNOLOGIES,BLANC AERO TECHNOLOGIES,76.19
25,UNIVERSITE DE MONTREAL,UNIVERSITE DE TOULON,76.19
26,UNIVERSITE DE LAUSANNE,UNIVERSITE DE TOULON,76.19
27,BLANC AERO TECHNOLOGIES,CEPRIM TECHNOLOGIES,76.19
28,ALSTOM TRANSPORT SA,ALSTOM TRANSPORT SA. LE CREUSOT,76.00
29,THE UNIVERSTY OF MELBOURNE,THE UNIVERSITY OF SYDNEY,76.00

In [102]:
company_replacements_75_80 = {
    "UNIVERSIDAD DE OVIEDO": "UNIVERSITY OF OVIEDO",

    "MANUFACTURE HORLOGERE VALFLEURIER (GROUPE RICH...":
        "MANUFACTURE HORLOGERE VALFLEURIER",
}

df["Entreprise"] = df["Entreprise"].replace(company_replacements_75_80)

print("Nombre d'entreprises :", df["Entreprise"].nunique())

Nombre d'entreprises : 1105

In [105]:
from pathlib import Path

OUTPUT_PATH = Path("data/processed/stages_cleaned.xlsx")
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

df.to_excel(OUTPUT_PATH, index=False)

print(f"Fichier sauvegardé : {OUTPUT_PATH.resolve()}")
print(f"Shape : {df.shape}")

Fichier sauvegardé : C:\Users\LENOVO YOGA SLIM 6i\Desktop\rag-pfe-data\notebooks\data\processed\stages_cleaned.xlsx
Shape : (2292, 23)

In [ ]:
import pandas as pd

df = pd.read_excel("data/processed/stages_cleaned.xlsx")

print(df.shape)
display(df.head())